version: '3'
services:

  db:
    image: postgres:latest
    container_name: meu-postgres
    ports:
      - "3600:5432"
    volumes:
      - /var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=root